name: bytebot

services:
  bytebot-desktop:
    image: ghcr.io/bytebot-ai/bytebot-desktop:edge
    shm_size: "2g"
    restart: unless-stopped
    hostname: computer
    privileged: true
    environment:
      - DISPLAY=:0

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bytebotdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bytebot-agent:
    image: ghcr.io/bytebot-ai/bytebot-agent:edge
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/bytebotdb
      - BYTEBOT_DESKTOP_BASE_URL=http://bytebot-desktop:9990
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres

  bytebot-ui:
    image: ghcr.io/bytebot-ai/bytebot-ui:edge
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BYTEBOT_AGENT_BASE_URL=http://bytebot-agent:9991
      - BYTEBOT_DESKTOP_VNC_URL=http://bytebot-desktop:9990/websockify
    depends_on:
      - bytebot-agent

volumes:
  postgres_data:
