name: bytebot

services:
  bytebot-ui:
    image: ghcr.io/bytebot-ai/bytebot-ui:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - bytebot-desktop

  bytebot-desktop:
    # Build from source
    # build:
    #   context: ../packages/
    #   dockerfile: bytebotd/Dockerfile
    # Use pre-built image
    image: ghcr.io/bytebot-ai/bytebot-desktop:edge
    shm_size: "2g"
    restart: unless-stopped
    hostname: computer
    privileged: true
    environment:
      - DISPLAY=:0

  bytebot-agent:
    # Build from source
    # build:
    #   context: ../packages/
    #   dockerfile: bytebot-agent/Dockerfile
    # Use pre-built image
    image: ghcr.io/bytebot-ai/bytebot-agent:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bytebot
      - POSTGRES_USER=bytebot
      - POSTGRES_PASSWORD=bytebot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bytebot -d bytebot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
